### ISSUE TITLE
I need your help collecting games. 

### ISSUE THREAD

**Issue by Cscuile** [Cscuile/BetaOne#1]
The goal is to collect as many high quality games as possible. Human games should be avoided. Please just paste a link to the source games.

**Comment by Geisard** [comment]
A few PGNs of very high quality Correspondence Chess games in the last 10 years. Only CC IMs and GMs, games.
https://www.iccf.com/GetEventPGN.aspx?id=31341
https://www.iccf.com/GetEventPGN.aspx?id=52852
https://www.iccf.com/GetEventPGN.aspx?id=60510
https://www.iccf.com/GetEventPGN.aspx?id=65430
https://www.iccf.com/GetEventPGN.aspx?id=37632
https://www.iccf.com/GetEventPGN.aspx?id=18349
https://www.iccf.com/GetEventPGN.aspx?id=65430

**Comment by Cscuile** [comment]
Thank you! Downloaded!

**Comment by Cscuile** [comment]
Hello! I wanted to ask before I did anything. Would you like me to credit you for helping us collect games?

The format I will use will be:
Cscuile (PGN Game Collection) 

Thank you!
